<a href="https://colab.research.google.com/github/mohamadfaisalbashir/scikit-learn-cookbook/blob/main/01_Common_Conventions_and_API_Elements_of_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Common Conventions and API Elements of scikit-learn**
This notebook covers the Common Conventions and API Elements of scikit-learn:

1. Introduction to scikit-learn's design philosophy
2. Understanding estimators
3. Transformers and the transform() method
4. Handling custom estimators and transformers
5. Pipelines and workflow automation
6. Common attributes and methods
7. Hyperparameter tuning with search methods
8. Working with metadata: Tags and more
9. Best practices for API usage

## **1. Introduction to scikit-learn's design philosophy**

Scikit-learn's design is centered around a few core principles: consistency, simplicity, modularity, and reusability. The library offers a unified interface where most models follow a similar pattern: they use fit() to train the model, predict() to make predictions, and transform() to manipulate data. This consistency allows users to easily switch between models and build complex workflows by chaining these modular components together.

## **2. Understanding estimators**

Estimators are object-oriented programming (OOP) objects that implement algorithms for learning from data. Every estimator follows a consistent interface with two essential methods: fit() to learn from the data and predict() to make predictions on new data. Scikit-learn also offers a shortcut method, fit_predict(), which is often applied in unsupervised learning scenarios (like clustering) where the data does not contain a target variable.

Code Example 1: Linear Regression (fit and predict)

In [1]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Example data
X = np.array([[1], [2], [3], [4], [5]]) # Feature matrix
y = np.array([1, 2, 3, 3.5, 5]) # Target values

# Create and fit the model
model = LinearRegression()
model.fit(X, y)

# Predict values for new data
X_new = np.array([[6], [7]])
predictions = model.predict(X_new)
print(predictions)

[5.75 6.7 ]


Code Example 2: KMeans (fit_predict)

In [2]:
# Fit_predict is not used in LinearRegression,
# but as an example for clustering:
from sklearn.cluster import KMeans

# Example data
X = np.array([[1], [2], [3], [4], [5]])

# KMeans Clustering example
kmeans = KMeans(n_clusters=2)
labels = kmeans.fit_predict(X)
print(labels)

[0 0 0 1 1]


## **3. Transformers and the transform() method**

In scikit-learn, transformers are tools that modify data by applying transformations like scaling, normalization, or encoding to prepare it for modeling. They use the fit() method to learn necessary parameters from the data and the transform() method to apply those transformations. There is also a fit_transform() shortcut that allows users to perform both steps in one command to make workflows more efficient.

Code Example 1: StandardScaler using fit then transform

In [3]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Example data
X = np.array([[1, 2], [3, 4], [5, 6]])

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler on the data
scaler.fit(X)

# Transform the data
X_scaled = scaler.transform(X)
print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


Code Example 2: Using fit_transform in one step

In [4]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Example data
X = np.array([[1, 2], [3, 4], [5, 6]])

# Create a StandardScaler instance and
# fit transform the data in one step
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


## **4. Handling custom estimators and transformers**

Scikit-learn's API is extensible, meaning developers can create custom machine learning algorithms or data transformations that integrate seamlessly into existing workflows. This is achieved by subclassing BaseEstimator() and using mixin classes. A mixin is a way to extend the functionality of classes without using traditional inheritance, allowing programmers to share code easily between different classes.

## **5. Pipelines and workflow automation**

Pipelines provide a structured way to automate machine learning workflows by chaining together multiple sequential steps, such as data preprocessing, model training, and prediction, into a single object. This approach is tightly linked to MLOps (Machine Learning Operations), which focuses on automating the process of developing, testing, deploying, and maintaining models in production environments.

## **6. Common attributes and methods**

To help users look inside and understand a model's inner workings, scikit-learn models share several key attributes and methods. For instance, linear models use attributes like coef_ and intercept_ to store the learned coefficients and intercepts. Similarly, models share the score() method to evaluate performance, returning default metrics like accuracy for classifiers or $R^{2}$ for regressors.

Code Example: Accessing Linear Model Attributes

In [5]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Example data
X = np.array([[1], [2], [3], [4], [5]]) # Feature matrix
y = np.array([1, 2, 3, 3.5, 5]) # Target values

# Create and fit the model
model = LinearRegression()
model.fit(X, y)

# Access coefficients (slope of the linear model)
print("Coefficients:", model.coef_)

# Access y-intercept
print("Intercept:", model.intercept_)

# Use score() method to evaluate the model (R-squared value)
print("Model R-squared:", model.score(X, y))

Coefficients: [0.95]
Intercept: 0.04999999999999938
Model R-squared: 0.9809782608695652


## **7. Hyperparameter tuning with search methods**

Scikit-learn makes optimizing candidate models easier with built-in search methods like GridSearchCV() and RandomizedSearchCV(). The library also allows a manual approach: the set_params() method lets users adjust hyperparameters programmatically, while get_params() retrieves the current hyperparameter settings.

Code Example: Setting and Getting Hyperparameters

In [6]:
from sklearn.ensemble import RandomForestClassifier

# Create a RandomForestClassifier model
model = RandomForestClassifier()

# Set hyperparameters prior to training using set_params()
model.set_params(n_estimators=100, max_depth=10, random_state=42)

# Check the updated parameters
print(model.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}


## **8. Working with metadata: Tags and more**
Scikit-learn uses metadata, such as estimator tags, to control how models behave in various contexts and detail their capabilities, like whether they can handle multi-output data or missing values. It also features metadata routing, a feature that allows users to control how metadata (like sample weights or group labels) is dynamically passed between router and consumer objects in a pipeline.

## **9. Best practices for API usage**

To ensure your code remains clear, modular, and maintainable, keep these best practices in mind:

- **Uniform API:** All estimators follow the basic pattern of fit(), transform(), and predict().

- **Data preprocessing:** Always preprocess your data using tools from sklearn.preprocessing before feeding it to the model.

- **Pipelines:** Use the Pipeline() class to chain operations together for complex workflows.

- **Cross-validation:** Use techniques from sklearn.model_selection to evaluate model performance reliably.

- **Hyperparameter tuning:** Optimize your model using tools like GridSearchCV() or RandomizedSearchCV().